#!/bin/bash

# Shell script wrapper for clip
# This script presumes that all of the files are stored with the same directory
# structure and relation to each other as in the git repository, but it can be
# any working directory as long as the structure is the same.

# Get the directories of the files.
DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
LIBDIR="$DIR/lib"
SRCDIR="$DIR/src"

# Check to make sure the script file is in the same directory.
if ! [ -a "$SRCDIR/main.py" ]; then
    echo "Could not find main.py; Make sure main.py is in the 'src' directory."
    exit 1
fi

# If there isn't a venv already created, create one.
if ! [ -d "$LIBDIR/venv" ]; then
    # Check to make sure the requirements.txt file is in the same directory.
    if ! [ -a "$LIBDIR/requirements.txt" ]; then
        echo "Could not find requirements.txt; Make sure requirements.txt and clip are in the same directory."
        exit 1
    fi
    echo "Downloading Python dependencies..."
    # Create the venv, activate it, install the dependencies, and then deactivate venv.
    python -m venv "$LIBDIR/venv"
    source "$LIBDIR/venv/bin/activate"
    pip install -q -r "$LIBDIR/requirements.txt"
    deactivate
fi

# Activate the venv
source "$LIBDIR/venv/bin/activate"
cd "$DIR"

# Run the main script
# Use $@ to directly pass arguments to the script
python "$SRCDIR/main.py" "$@"
# Deactivate the venv.
deactivate
