#!/bin/bash
# Shell script installer for CLIp
# This script accepts no arguments, but expects root privileges. It attempts to
# create an installation executable file here by default: /usr/local/bin/clip
# The created script just runs the "./clip" script in this directory.

# To uninstall, remove the file as root, e.g.: sudo rm -f /usr/local/bin/clip

# Running this installation script when an installation already exists will
# cause it to attempt to clean and re-install the program.

# This script presumes that all of the files are stored with the same directory
# structure and relation to each other as in the CLIp git repository.

# Get the directories of the files.
DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
LIBDIR="$DIR/lib"
SRCDIR="$DIR/src"

# Check to make sure the directory structure is intact
if ! [ -a "$SRCDIR/main.py" ]; then
    printf "\nError: could not find main.py; Make sure main.py is in the 'src' directory and is accessible by this script.\n"
    exit 1
fi

# Set up installation
INSTALL_DIR="/usr/local/bin"
INSTALL_FILE="$INSTALL_DIR/clip"

# Delete previous installation file (if exists)
if [ -a "$INSTALL_FILE" ]; then
    rm -f "$INSTALL_FILE" &> /dev/null
    # If delete fails, let user know they need root permissions
    if [ -a "$INSTALL_FILE" ]; then
        printf "Error: Could not clean previous installation. Please try running with root permissions.\n"
        exit 1
    fi
fi

# Create installation file
touch "$INSTALL_FILE" &> /dev/null
# If touch fails to create the install file, let the user know they need root permissions.
if ! [ -a "$INSTALL_FILE" ]; then
    printf "Error: Could not install to /usr/local/bin. Please try running with root permissions.\n"
    exit 1
fi

# Create installation file
printf "#!/bin/bash\n" >> "$INSTALL_FILE"
printf "# Script for running CLIp generated during installation.\n" >> "$INSTALL_FILE"
printf "# To uninstall, just remove this file as root, e.g.: sudo rm -f $INSTALL_FILE\n\n" >> "$INSTALL_FILE"
printf "$DIR/clip \"\$@\"" >> "$INSTALL_FILE"
# Set installation file permissions
chmod 0755 "$INSTALL_FILE"
chown root:root "$INSTALL_FILE"

if [ -a "$INSTALL_FILE" ]; then
    printf "Installation finished!\nConsider reloading your terminal for all changes to take effect.\n"
fi
